- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
    - name: update apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - include: tasks/core-setup.yml
    - include: tasks/dotfiles.yml
    - include: tasks/git-setup.yml
    - include: tasks/lazygit.yml
    - include: tasks/lsp.yml
    - include: tasks/node.yml
    - include: tasks/npm-packages.yml
    - include: tasks/nvim.yml
    - include: tasks/other-stuff.yml
    - include: tasks/ssh.yml
    - include: tasks/zsh.yml
