- name: installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow

- name: cloning .dotfiles
  ansible.builtin.git:
    repo: "git@github.com:kikovsky/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    update: yes
    accept_hostkey: yes
  tags:
    - install
    - dotfiles
    - stow

- name: stow dotfiles
  shell: cd $HOME/.dotfiles && ./ubuntu
  tags:
    - install
    - dotfiles
    - stow
